workflows:
  flutter-game-build:
    name: Build Flutter Game
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Run tests
        script: flutter test
      - name: Build EXE
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your-email@example.com

scripts:
  - name: Get dependencies
    script: |
      cd your_project_folder  # Only if needed
      flutter pub get

